### ISSUE TITLE
Dotting my i's and j's sometimes doesn't work

### ISSUE THREAD

**Issue by StephenHaney** [steveruizok/perfect-freehand#1]
First, awesome library (again!).

I was enjoying myself, swirling and curving away, when suddenly I noticed a few of my i's lost their dots.

macOS Mac Mini M1
Chrome
Drawing with a mouse

Here's a screen cap:

https://user-images.githubusercontent.com/4045376/108576562-f5f36600-72d2-11eb-874e-114a95e7c0ea.mov

**Comment by steveruizok** [comment]
Should be fixed in 0.2.0! I may still tweak the outline shape for dots / short marks, but you're at least bound to get a shape now.
