### ISSUE TITLE
Suggestion: clear selection

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [steveruizok/perfect-freehand#15]
As a user, I'd like to be able to drag-and-select an area on the canvas and delete a certain path. Motivation: Sometimes, the path I want to delete is too far back in history. I don't want to undo other work, but I also don't want to clear everything.

Maybe there could be a select tool/mode that users can toggle. In this mode, drawing is disabled, and dragging the mouse instead selects an area on the screen. The individual selection can then be deleted (I suppose there would need to be a separate icon for this to avoid confusion with the clear-all button).

By the way, thanks for making this excellent tool :)

**Comment by steveruizok** [comment]
Hey Aleksander, thanks for the idea. This example site is just meant as a quick demo for the library. If you want to have more control, I'd recommend trying out Excalidraw, which has implemented perfect-freehand. I also have a work in progress where you'll be able to do the kind of selection that you're asking about:

![Kapture 2021-06-09 at 16 16 42](https://user-images.githubusercontent.com/23072548/121382144-3a684780-c93e-11eb-9f23-a11de6af0c2e.gif)

This project isn't quite ready, so it's currently only available for my Github sponsors.

Separate from that, I may be working on an "eraser" function for the library later this year. If I get that figured out, I'll have it implemented on the example site.

**Comment by AleksandrHovhannisyan** [comment]
Excalidraw is great! Did not know that your library powers its drawing tools. Thanks!

**Comment by steveruizok** [comment]
Just the free draw tool, rough.js handles the rest. :)
