### ISSUE TITLE
Pointer events cancelled by touch-action on Chrome

### ISSUE THREAD

**Issue by apostolos** [steveruizok/perfect-freehand#2]
Pointer events (e.g. [pointermove](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointermove_event)) are being cancelled by a browser's touch action. This breaks Chrome on Android (or desktop Chrome with touch simulation enabled).

An easy fix is to put the following property to the svg element:

```css
touch-action: none;
```

## Before
![image](https://user-images.githubusercontent.com/41679/108607523-8613d700-73c9-11eb-8784-9530b3f5dd78.png)

## After
![image](https://user-images.githubusercontent.com/41679/108607539-9fb51e80-73c9-11eb-9b6e-cf7c5059ee6c.png)

**Comment by steveruizok** [comment]
Dude, my hero. Just pushed! Could you confirm that it's working? 

https://perfect-freehand-example.vercel.app/
https://biwyi.csb.app/

**Comment by apostolos** [comment]
Works perfectly, thank you! 👍 

(you should probably document the requirement, it's easy to miss if someone hasn't messed with pointer events before)
