### ISSUE TITLE
[Bug] getStrokes returns NaN when provided two or more points with the same coordinates

### ISSUE THREAD

**Issue by tarngerine** [steveruizok/perfect-freehand#29]
```
getStroke([
  [1, 1],
  [1, 1],
])
```

ends up with

<img width="175" alt="image" src="https://user-images.githubusercontent.com/1629901/133128429-df0b713e-3edf-469a-9790-b7def4dfee6d.png">

this can happen when sampling points on each frame (as opposed to onmousemove)

im not sure what the best expected result is, maybe drawing the points as a single dot/circle? or return an empty array if any of the results are NaN

**Comment by steveruizok** [comment]
Good catch! Fixed in https://github.com/steveruizok/perfect-freehand/commit/629d7676258936730d13ecb767d00f79a9cd0e68
