### ISSUE TITLE
[feature] Reduce import dependencies (e.g. zustand)

### ISSUE THREAD

**Issue by tarngerine** [steveruizok/perfect-freehand#31]
Hi, just running through all the package deps, noticed that zustand was being added?

<img width="714" alt="image" src="https://user-images.githubusercontent.com/1629901/133164654-b97b1a61-019d-4891-86b1-8c3b1a3b487e.png">

@tldraw/core also comes with react-use-gesture
<img width="719" alt="image" src="https://user-images.githubusercontent.com/1629901/133164672-bf815016-cd07-41ff-bd46-f34723643d98.png">

Would be nice to slowly reduce the dependencies here — thanks!

**Comment by steveruizok** [comment]
Good catch! I've removed those dependencies from the package. (It's back to zero deps). The root package.json will show dependencies from the dev server, which is used for the example site; but the deps in the packages/perfect-freehand/package.json are now clean.

**Comment by steveruizok** [comment]
Closed in https://github.com/steveruizok/perfect-freehand/commit/1f9b57500bf9750f0fe04d8ab97460c2b65d96da
