### ISSUE TITLE
[feature] Ability to reset drawing settings?

### ISSUE THREAD

**Issue by ThomasRettig** [steveruizok/perfect-freehand#39]
It would be useful if there was a reset function that resets my customised drawing settings back to the default.

For example, if I arbitrarily decrease the ```size```, increase the ```thickness```, increase the ```streamline```, and change the ```easing``` to something else, I want the ability to reset these settings back to the default in one shot, rather than having to manually adjust them back one-by-one.

Thanks!

**Comment by steveruizok** [comment]
This is for the example project, right?

 If I understand correctly, then this button should reset everything in the example project. 

![image](https://user-images.githubusercontent.com/23072548/143060940-9fdf75df-8e23-48ce-aa93-dc41c19ad932.png)

You can also reset individual settings by double-clicking on the setting's label.
