### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [steveruizok/perfect-freehand#5]
## Description 

Hi @steveruizok 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/perfect-freehand/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Prefer ternary operator [here](https://deepsource.io/gh/HarshCasper/perfect-freehand/issue/JS-D009/)
- Found non-null assertions [here](https://deepsource.io/gh/HarshCasper/perfect-freehand/issue/JS-0339/)
- Detected unused variables [here](https://deepsource.io/gh/HarshCasper/perfect-freehand/issue/JS-0356/)
- Detected empty functions [here](https://deepsource.io/gh/HarshCasper/perfect-freehand/issue/JS-0321/)
- Found weak hashing functions [here](https://deepsource.io/gh/HarshCasper/perfect-freehand/issue/JS-D003/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the commonly occurring issues, I can help you set that up :)

**Comment by steveruizok** [comment]
Hey, thanks for showing me this. Most of the issues are from the example project which likely doesn't need as close analysis. I'll come back to DeepSource and other analysis again before a 1.0.0 release.
