### ISSUE TITLE
[Bug] Explicit ESM declaration

### ISSUE THREAD

**Issue by Redemption198** [steveruizok/perfect-freehand#53]
This module is being used by [Drauu](https://github.com/antfu/drauu) which has an integration with [VueUse](https://github.com/vueuse/vueuse) and can be used with Nuxt (Vue). Since Nuxt 3 uses Vite as a bundler by default and it only allows the use of ESM modules, when it tries to bundle `perfect-freehand` the following error occurs: 

import { getStroke } from "perfect-freehand";
         ^^^^^^^^^
SyntaxError: Named export 'getStroke' not found. The requested module 'perfect-freehand' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'perfect-freehand';
const { getStroke } = pkg;

I was able to "fix" it by adding the following lines into the `package.json` inside `node_modules`:

"type": "module",
"exports": {
    ".": {
      "types": "./dist/types/index.d.ts",
      "import": "./dist/esm/index.js"
    }
}

I'm not sure if this may cause some problems that's why I'm opening an Issue

**Comment by steveruizok** [comment]
Awesome, want to make a PR?

**Comment by Redemption198** [comment]
> Awesome, want to make a PR?

Sure. It's here https://github.com/steveruizok/perfect-freehand/pull/55

**Comment by Ursuss21** [comment]
Hello, I have an issue connected to this one in [here](https://github.com/wobsoriano/v-perfect-signature/issues/17). I guess the only thing remaining to do is to release the current version, if that's not a big deal.

**Comment by garand** [comment]
This has been released. `v1.2.2`
