### ISSUE TITLE
[documentation] Documentation of "last" parameter default doesn't match code

### ISSUE THREAD

**Issue by kepstin** [steveruizok/perfect-freehand#65]
In the current version of the [README](https://github.com/steveruizok/perfect-freehand/blob/6ae88f4d77d4092e81b8aba3d5833d94dc80636c/README.md#options), the `last` option is documented as having a default of `true`:

| Property           | Type     | Default | Description                                           |
| ------------------ | -------- | ------- | ----------------------------------------------------- |
| `last`             | boolean  | true    | Whether the stroke is complete.                       |

However, in the code - [`getStrokeOutlinePoints`](https://github.com/steveruizok/perfect-freehand/blob/58c5fce6936c9b67dfd21fada83266dc988a01a1/packages/perfect-freehand/src/getStrokeOutlinePoints.ts#L51) and [`getStrokePoints`](https://github.com/steveruizok/perfect-freehand/blob/58c5fce6936c9b67dfd21fada83266dc988a01a1/packages/perfect-freehand/src/getStrokePoints.ts#L22) - the actual default of the `last` option (assigned to the `isComplete` variable) is set to `false`.

I'm not sure what the intention is here, but to preserve the behaviour of the library it might be best to leave the default as `false` and update the documentation to match.

**Comment by steveruizok** [comment]
Fixed!
