### ISSUE TITLE
[feature] currentcolor option in color palette

### ISSUE THREAD

**Issue by wesort** [steveruizok/perfect-freehand#68]
Request to add option to set the color `currentcolor`.

Useful in website:
- to set SVG color in ancestor mark-up
- to allow for site theming (ie: switching from light to dark mode)

? eyedropper icon?

**Comment by steveruizok** [comment]
The library itself doesn't really address things like color, it just generates the points of a polygon. Do you mean in the example project (ie perfect-freehand.com?)
