### ISSUE TITLE
[feature] Shape recognition

### ISSUE THREAD

**Issue by SimonSimCity** [steveruizok/perfect-freehand#69]
I'd be interested in shape recognition. [Found this](https://inkscape.org/~qpad/%E2%98%85shape-recognition) - maybe there's something in JavaScript for SVG as well ... 🤗

The idea was taken by https://helpx.adobe.com/illustrator/using/tool-techniques/shaper-tool.html

**Comment by steveruizok** [comment]
This one is out of scope for this project—we're really just about the ink itself. I'd love to see a project like this though!
